config/routes.rb
Rails.application.routes.draw do
  # get 'tasks', to: 'tasks#index'
  # post 'tasks', to: 'tasks#create'
  # get 'tasks/new', to: 'tasks#new'
  # get 'task/:id', to: 'tasks#show', as: 'task'
  # patch 'task/:id', to: 'tasks#update'
  # get 'task/:id/edit', to: 'tasks#edit', as: 'task_edit'
  # delete 'task/:id', to: 'tasks#destroy'
  resources :tasks
  patch 'task/:id/check', to: 'tasks#check', as: 'check_task'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :check]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  def check
    @task.completed = !@task.completed
    @task.save
    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container mt-5">
    <%= yield %>
  </div>
  <script src="https://kit.fontawesome.com/7b8fdf30c4.js" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tasks/_checkbox.html.erb
<%= link_to check_task_path(task), method: :patch do %>
  <% if task.completed %>
    <i class="fa-regular fa-square-check"></i>
  <% else %>
  <i class="fa-regular fa-square"></i>
  <% end %>
<% end %>

app/views/tasks/_form.html.erb
<%= simple_form_for(task) do |f| %>
  <%= f.input :title%>
  <%= f.input :details %>
  <% unless task.new_record? %>
    <%= f.input :completed %>
  <% end %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>
<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>
<ul>
  <% @tasks.each do |task| %>
    <li>
      <%= render 'checkbox', task: task%>
      <%= link_to task.title, task_path(task) %>
      <%= link_to task_path(task), method: :delete, data: { confirm: "Are you sure?" } do %>
            <i class="fa-regular fa-trash-can"></i>
      <% end %>
    </li>
  <% end %>
</ul>

<%= link_to 'Add a new task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>
<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h1><%= @task.title %> <%= render 'checkbox', task: @task%></h1>
<p><%= @task.details %></p>

<div>
  <%= link_to 'Edit task', edit_task_path %>
  <%= link_to "Delete",
        task_path(@task),
        method: :delete,
        data: { confirm: "Are you sure?" } %>
  <%= link_to 'Back to list', tasks_path %>
</div>